# Generated by Django 5.0.1 on 2024-01-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_participants_message_is_group_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_group_chat',
            field=models.BooleanField(default=True),
        ),
    ]
