# Generated by Django 5.0.1 on 2024-01-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_group_name_chatroom_is_group_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='is_group_chat',
            field=models.BooleanField(default=False),
        ),
    ]
